// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVTE6zlR3ja1-m8sjO-CgYJrO06eVr3c',
    appId: '1:790779504357:web:dde9deba0a5bb4cc5b560c',
    messagingSenderId: '790779504357',
    projectId: 'dermarasa',
    authDomain: 'dermarasa.firebaseapp.com',
    storageBucket: 'dermarasa.appspot.com',
    measurementId: 'G-4MS7T16ZZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRa9sV3VSJ8BZyBErRw1977C_RG8zcdo',
    appId: '1:790779504357:android:6f00f545e242c4b35b560c',
    messagingSenderId: '790779504357',
    projectId: 'dermarasa',
    storageBucket: 'dermarasa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8j_1uRpsPviM4rOXoq5bJN-WYvTJCpuI',
    appId: '1:790779504357:ios:ba7fec078758e6415b560c',
    messagingSenderId: '790779504357',
    projectId: 'dermarasa',
    storageBucket: 'dermarasa.appspot.com',
    iosClientId:
        '790779504357-gd9gitbrhhp2msm3mt6mg9vd0dkmsj5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dermarasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8j_1uRpsPviM4rOXoq5bJN-WYvTJCpuI',
    appId: '1:790779504357:ios:39685a810d1226f25b560c',
    messagingSenderId: '790779504357',
    projectId: 'dermarasa',
    storageBucket: 'dermarasa.appspot.com',
    iosClientId:
        '790779504357-vq63ham502v264jrl2lc5ilchu3b2jvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dermarasa.RunnerTests',
  );
}
